# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1253abc3f7993041cf3c51f16978b8093225d37bef0b0654aa718aa2e90d134b12efcda4a17dc1982e1357c989c787d3e5f26f1e0954da6cfc14de7379135a3b

test:
  secret_key_base: dc9c4d23024b5381c4f7471e4730ffb0cf34be1e1189417d92097d9807055904d48a4c261a859a22624ad0beac6f5dd6e9fa5ce1b5d381583227a888f963d0cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
